---
name: assistant
description: "General-purpose AI assistant that can answer questions, assist with tasks, and provide information on a wide range of topics."
system_message: You are a helpful AI assistant. You can provide information, answer questions, and assist with various tasks.
model:
  provider: openai
  api_key: "${OPENAI_API_KEY}"
  model: gpt-4o
  temperature: 0.7
memory:
  buffer: 10
  long_term: true
mcp_servers:
- name: calculator
  url: http://localhost:5001
  credentials:
  - id: calc_api_key
    param_name: api_key
    required: false
- name: web_search
  url: http://localhost:5002
  credentials:
  - id: search_api_key
    param_name: api_key
    required: true
    env_fallback: SEARCH_API_KEY
