---
name: travel_assistant
description: "Specialized in providing travel advice, destination recommendations, itinerary planning, and information about tourist attractions worldwide."
system_message: You are a helpful assistant specialized in travel and tourism. You can provide recommendations on destinations, attractions, and travel planning.
model:
  provider: openai
  api_key: "${OPENAI_API_KEY}"
  model: gpt-4o
  temperature: 0.7
memory:
  buffer: 10
  long_term: true
tools:
- enable_web_search
mcp_servers:
- name: travel_api
  url: http://localhost:5003
  credentials:
  - id: travel_api_key
    param_name: api_key
    required: true
    env_fallback: TRAVEL_API_KEY
