---
name: weather_assistant
description: "Specialized in providing weather forecasts, answering questions about climate and weather phenomena, and reporting current conditions in various locations worldwide."
system_message: You are a helpful assistant that can check the weather. Use the Weather
  API when asked about weather conditions.
model:
  provider: openai
  api_key: "${OPENAI_API_KEY}"
  model: gpt-4o
  temperature: 0.7
memory:
  buffer_size: 10
  buffer_multiplier: 10
  long_term: true
mcp_servers:
- name: weather
  url: http://localhost:5001
  credentials:
  - id: weather_api_key
    param_name: api_key
    required: true
    env_fallback: WEATHER_API_KEY
- name: web_search
  url: http://localhost:5002
  credentials:
  - id: search_api_key
    param_name: api_key
    required: true
    env_fallback: SEARCH_API_KEY
